# Generated by Django 4.2.13 on 2024-07-12 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="from_user",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="to_user",
        ),
        migrations.DeleteModel(
            name="FriendRequest",
        ),
        migrations.DeleteModel(
            name="Notification",
        ),
    ]
