# Generated by Django 4.2.13 on 2024-07-16 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_customuser_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
