# Generated by Django 4.2.13 on 2024-07-18 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameSession',
        ),
    ]
