# Generated by Django 4.2.13 on 2024-07-09 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_customuser_is_staff_alter_customuser_avatar_and_more'),
        ('pages', '0004_gamesession'),
    ]

    operations = [
    ]
